package fi.oph.yki.model;

public enum EmailType {
  LOGIN,
  LOGIN_QUEUE,
  LOGIN_RENEW,
  PAYMENT,
  PAYMENT_FROM_QUEUE,
  PAYMENT_SUCCESS,
  FREE_REGISTRATION,
  FREE_REGISTRATION_FROM_QUEUE,
  QUEUE,
  CANCEL_REGISTRATION,
  CANCEL_FREE_REGISTRATION,
  CANCEL_QUEUE,
  TRANSFER_CONFIRMATION,
  EVALUATION_PAYMENT_SUCCESS,
  EVALUATION_PAYMENT_KIRJAAMO,
}
