package fi.oph.yki.model;

public enum EmailType {
  ENROLLMENT_CONFIRMATION,
  ENROLLMENT_TO_QUEUE_CONFIRMATION,
  ENROLLMENT_APPOINTMENT_AUTH_LINK,
  ENROLLMENT_CONTACT_REQUEST,
  ENROLLMENT_APPOINTMENT_CONFIRMATION,
}
