export enum APIEndpoints {
  Authenticate = '/yki/auth/',
  CountryCodes = '/yki/api/code/maatjavaltiot2',
  ExamSessions = '/yki/api/exam-session',
  ExamSession = '/yki/api/exam-session/:examSessionId',
  ExamSessionQueue = '/yki/api/exam-session/:examSessionId/queue',
  Evaluations = '/yki/api/evaluation',
  Evaluation = '/yki/api/evaluation/:evaluationId',
  EvaluationOrder = '/yki/api/evaluation/:evaluationId/order',
  EvaluationOrderDetails = '/yki/api/evaluation/order/:evaluationOrderId',
  InitRegistration = '/yki/api/registration/init',
  IdentifyRegistration = '/yki/api/registration/identify',
  LoginLink = '/yki/api/login-link',
  Logout = '/yki/auth/logout',
  Registration = '/yki/api/registration/:registrationId',
  SubmitRegistration = '/yki/api/registration/:registrationId/submit',
  User = '/yki/api/user/identity',
  OpenRegistrations = '/yki/api/user/open-registrations',
  PersonDetails = '/yki/api/person',
  CancelUserRegistration = '/yki/api/person/registration/:registrationId',
  TransferEnrollment = '/yki/api/person/registration/:registrationId/relocate',
  ConfirmRegistration = '/yki/api/person/registration/:registrationId/confirm',
  RedirectToPayment = '/yki/api/payment/v3/:registrationId/redirect?lang=:lang',
}

export enum PaymentStatus {
  Success = 'payment-success',
  Cancel = 'payment-cancel',
  Error = 'payment-error',
}
