enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  "opetushallitus":
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_REGISTRY_TOKEN-GITHUB_TOKEN}

yarnPath: .yarn/releases/yarn-3.2.0.cjs
