enableGlobalCache: true

enableTelemetry: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmScopes:
  opetushallitus:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_REGISTRY_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
