compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmScopes:
  opetushallitus:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_REGISTRY_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

# Age gate prevents installing newly released packages, to mitigate supply
# chain attacks
npmMinimalAgeGate: 1440
# To allow specific packages:
#npmMinimumReleaseAgeExclude:
#  - package@version

npmPreapprovedPackages:
  - "@opetushallitus/oph-design-system@2.0.0"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
