enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

npmScopes:
  "@opetushallitus":
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
