enableGlobalCache: true

enableTelemetry: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmScopes:
  opetushallitus:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_REGISTRY_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
