FROM node:16.16.0-alpine

RUN corepack enable

ARG GITHUB_REGISTRY_TOKEN

# Create app directory
WORKDIR /app/reactjs

# Copy workspace config
COPY package*.json yarn.lock webpack.common.js ./
COPY .yarn/releases ./.yarn/releases
COPY .yarn/plugins ./.yarn/plugins
COPY .yarnrc.yml ./

# Copy packages
COPY ./packages/otr ./packages/otr

RUN yarn install

ENTRYPOINT [ "yarn", "otr:start:docker-compose" ]
