FROM node:16.14.2-alpine

RUN corepack enable

ARG GITHUB_REGISTRY_TOKEN

# Create app directory
WORKDIR /app/reactjs

# Copy workspace config
COPY package*.json yarn.lock ./
COPY .yarn/releases ./.yarn/releases
COPY .yarnrc.yml ./

# Copy packages
COPY ./packages/akt ./packages/akt

RUN yarn install

ENTRYPOINT [ "yarn", "akt:start:docker-compose" ]
