package fi.oph.akr.audit;

import fi.vm.sade.auditlog.Operation;

public enum AkrOperation implements Operation {
  LIST_TRANSLATORS,
  CREATE_TRANSLATOR,
  GET_TRANSLATOR,
  UPDATE_TRANSLATOR,
  DELETE_TRANSLATOR,
  CREATE_AUTHORISATION,
  UPDATE_AUTHORISATION,
  UPDATE_AUTHORISATION_PUBLISH_PERMISSION,
  DELETE_AUTHORISATION,
  CREATE_MEETING_DATE,
  UPDATE_MEETING_DATE,
  DELETE_MEETING_DATE,
  CREATE_EXAMINATION_DATE,
  DELETE_EXAMINATION_DATE,
}
