server:
  port: ${application.port:8080}
  compression:
    enabled: true
  servlet:
    context-path: "/akr"
spring:
  datasource:
    url: ${postgresql.url:jdbc:postgresql://localhost:6430/akr-postgres}
    username: ${postgresql.username:postgres}
    password: ${postgresql.password:postgres}
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  data:
    web:
      pageable:
        max-page-size: 10000
  web:
    resources:
      static-locations: classpath:static/
  thymeleaf:
    prefix: classpath:static/
    templateResolverOrder: 1
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/api/actuator"
      exposure:
        include: "health,info"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: false
  api-docs:
    path: /api/api-docs
    enabled: false
host:
  alb: ${virkailija.host.alb:localhost:${server.port}}
  virkailija: ${virkailija.host.virkailija:localhost:${server.port}}
cas:
  key: akr
  send-renew: false
  login-path: /login/cas
  logout-path: /cas/localLogout
  logout-success-path: /etusivu
  cookie-name: JSESSIONID
  service-url: ${virkailija.cas.service-url:http://localhost:${server.port}/akr}
  url: ${virkailija.cas.url:http://localhost:${server.port}/akr}
  login-url: ${virkailija.cas.login-url:http://localhost:${server.port}/login}
app:
  email:
    sending-enabled: ${email.sending-enabled:false}
    service-url: ${email.service-url:null}
