export const CLERK_TRANSLATOR_AUTHORISATION_ADD =
  'CLERK_TRANSLATOR_AUTHORISATION/ADD';
export const CLERK_TRANSLATOR_AUTHORISATION_ADD_ERROR =
  'CLERK_TRANSLATOR_AUTHORISATION/ADD_ERROR';
export const CLERK_TRANSLATOR_AUTHORISATION_ADD_SUCCESS =
  'CLERK_TRANSLATOR_AUTHORISATION/ADD_SUCCESS';
