export const CLERK_TRANSLATOR_OVERVIEW_LOAD = 'CLERK_TRANSLATOR_OVERVIEW/LOAD';
export const CLERK_TRANSLATOR_OVERVIEW_FETCH =
  'CLERK_TRANSLATOR_OVERVIEW/FETCH';
export const CLERK_TRANSLATOR_OVERVIEW_FETCH_SUCCESS =
  'CLERK_TRANSLATOR_OVERVIEW/FETCH_SUCCESS';
export const CLERK_TRANSLATOR_OVERVIEW_FETCH_FAIL =
  'CLERK_TRANSLATOR_OVERVIEW/FETCH_FAIL';
export const CLERK_TRANSLATOR_OVERVIEW_LOADING =
  'CLERK_TRANSLATOR_OVERVIEW/LOADING';

// Translator Details
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_TRANSLATOR_DETAILS =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_TRANSLATOR_DETAILS';
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_TRANSLATOR_DETAILS_SUCCESS =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_TRANSLATOR_DETAILS_SUCCESS';
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_TRANSLATOR_DETAILS_FAIL =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_TRANSLATOR_DETAILS_FAIL';
export const CLERK_TRANSLATOR_OVERVIEW_RESET_UPDATE =
  'CLERK_TRANSLATOR_OVERVIEW/RESET_UPDATE';
export const CLERK_TRANSLATOR_OVERVIEW_CANCEL_UPDATE =
  'CLERK_TRANSLATOR_OVERVIEW/CANCEL_UPDATE';

// Authorisation actions
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_AUTHORISATION_PUBLISH_PERMISSION =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_AUTHORISATION_PUBLISH_PERMISSION';
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_AUTHORISATION_PUBLISH_PERMISSION_SUCCESS =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_AUTHORISATION_PUBLISH_PERMISSION_SUCCESS';
export const CLERK_TRANSLATOR_OVERVIEW_UPDATE_AUTHORISATION_PUBLISH_PERMISSION_FAIL =
  'CLERK_TRANSLATOR_OVERVIEW/UPDATE_AUTHORISATION_PUBLISH_PERMISSION_FAIL';
export const CLERK_TRANSLATOR_OVERVIEW_DELETE_AUTHORISATION =
  'CLERK_TRANSLATOR_OVERVIEW/DELETE_AUTHORISATION';
export const CLERK_TRANSLATOR_OVERVIEW_DELETE_AUTHORISATION_SUCCESS =
  'CLERK_TRANSLATOR_OVERVIEW/DELETE_AUTHORISATION_SUCCESS';
export const CLERK_TRANSLATOR_OVERVIEW_DELETE_AUTHORISATION_FAIL =
  'CLERK_TRANSLATOR_OVERVIEW/DELETE_AUTHORISATION_FAIL';
