export const CLERK_TRANSLATOR_EMAIL_SEND = 'CLERK_TRANSLATOR_EMAIL/SEND';
export const CLERK_TRANSLATOR_EMAIL_SET = 'CLERK_TRANSLATOR_EMAIL/SET';
export const CLERK_TRANSLATOR_EMAIL_RESET = 'CLERK_TRANSLATOR_EMAIL/RESET';
export const CLERK_TRANSLATOR_EMAIL_SET_RECIPIENTS =
  'CLERK_TRANSLATOR_EMAIL/SET_RECIPIENTS';
export const CLERK_TRANSLATOR_EMAIL_SUCCESS = 'CLERK_TRANSLATOR_EMAIL/SUCCESS';
export const CLERK_TRANSLATOR_EMAIL_ERROR = 'CLERK_TRANSLATOR_EMAIL/ERROR';
export const CLERK_TRANSLATOR_EMAIL_CANCEL = 'CLERK_TRANSLATOR_EMAIL/CANCEL';
