export const MEETING_DATE_LOAD = 'MEETING_DATE/LOAD';
export const MEETING_DATE_LOADING = 'MEETING_DATE/LOADING';
export const MEETING_DATE_ERROR = 'MEETING_DATE/ERROR';
export const MEETING_DATE_RECEIVED = 'MEETING_DATE/RECEIVED';

export const MEETING_DATE_ADD_FILTER = 'MEETING_DATE/ADD_FILTER';

export const MEETING_DATE_ADD = 'MEETING_DATE/ADD';
export const MEETING_DATE_ADD_SUCCESS = 'MEETING_DATE/ADD_SUCCESS';
export const MEETING_DATE_ADD_ERROR = 'MEETING_DATE/ADD_ERROR';

export const MEETING_DATE_REMOVE = 'MEETING_DATE/REMOVE';
export const MEETING_DATE_REMOVE_SUCCESS = 'MEETING_DATE/REMOVE_SUCCESS';
export const MEETING_DATE_REMOVE_ERROR = 'MEETING_DATE/REMOVE_ERROR';

export const MEETING_DATE_REMOVE_CONFIRM = 'MEETING_DATE/REMOVE';
export const MEETING_DATE_REMOVE_CANCEL = 'MEETING_DATE/CANCEL';
