server:
  port: ${application.port:8083}
  compression:
    enabled: true
  servlet:
    context-path: "/yki"
spring:
  datasource:
    url: ${postgresql.url:jdbc:postgresql://localhost:5432/yki}
    username: ${postgresql.username:admin}
    password: ${postgresql.password:admin}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  web:
    resources:
      static-locations: classpath:static/
      cache:
        cachecontrol:
          max-age: 30d
      chain:
        cache: true
  thymeleaf:
    prefix: classpath:static/
    templateResolverOrder: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oauth2.issuer-uri:https://dev.otuva.opintopolku.fi/kayttooikeus-service}
          jwk-set-uri: ${oauth2.jwk-set-uri:https://dev.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks}
management:
  endpoints:
    access:
      default: none
    web:
      base-path: "/status"
      exposure:
        include: "health,info"
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
app:
  proxy-token: ${proxy-token:"03e2f9b3-d1de-4846-884e-80e6c3d0fae4"}
  koski:
    url: ${koski.url:null}
    user: ${cas.username:null}
    password: ${cas.password:null}
  clerk-enabled: ${clerk.enabled:false}
  email:
    sending-enabled: ${email.sending-enabled:false}
    service-url: ${email.service-url:null}
host:
  alb: ${virkailija.host.alb:localhost:${server.port}}
cas:
  key: yki-ui
  send-renew: false
  login-path: /login/cas
  logout-path: /cas/localLogout
  logout-success-path: /etusivu
  cookie-name: JSESSIONID
  onr-url: ${cas.onr-service-url:https://virkailija.untuvaopintopolku.fi/oppijanumerorekisteri-service}
  service-url: ${virkailija.cas.service-url:http://localhost:${server.port}/yki}
  url: ${virkailija.cas.url:http://localhost:${server.port}/yki}
  cas-url: ${virkailija.cas.url:https://virkailija.untuvaopintopolku.fi/cas}
  login-url: ${virkailija.cas.login-url:http://localhost:${server.port}/login}
  onr:
    username: ${cas.username:null}
    password: ${cas.password:null}
