package fi.oph.vkt.model.type;

public enum EnrollmentAppointmentStatus {
  COMPLETED,
  AWAITING_PAYMENT,
  CANCELED,
  EXPECTING_PAYMENT,
  WAITING_AUTHENTICATION,
  CANCELED_PAYMENT,
  ENROLLMENT_CREATED,
  CONTACT_CREATED,
}
