package fi.oph.yki.api.dto.oauth2;

public enum KituEvaluationState {
  ARVIOITAVA,
  ARVIOITU,
  TARKISTUSARVIOITAVA,
  TARKISTUSARVIOITU,
  TARKISTUSARVIOINTI_HYVAKSYTTY,
  UUSITTAVA,
  EI_SUORITUSTA,
  KESKEYTETTY,
}
