server:
  port: ${application.port:8081}
  compression:
    enabled: true
  servlet:
    context-path: "/otr"
spring:
  datasource:
    url: ${postgresql.url:jdbc:postgresql://localhost:6431/otr-postgres}
    username: ${postgresql.username:postgres}
    password: ${postgresql.password:postgres}
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  data:
    web:
      pageable:
        max-page-size: 10000
  web:
    resources:
      static-locations: classpath:static/
  thymeleaf:
    prefix: classpath:static/
    templateResolverOrder: 1
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/api/actuator"
      exposure:
        include: "health,info"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/api-docs
cas:
  key: otr
  send-renew: false
  login-path: /login/cas
  logout-path: /cas/localLogout
  logout-success-path: /etusivu
  cookie-name: JSESSIONID
  service: ${virkailija.cas.service:http://localhost:${server.port}/otr}
  url: ${virkailija.cas.url:http://localhost:${server.port}/otr}
  login: ${virkailija.cas.login:http://localhost:${server.port}/login}
host-virkailija: ${virkailija.host-virkailija:localhost:${server.port}}
otr:
  email:
    sending-enabled: ${email.sending-enabled:false}
    ryhmasahkoposti-service-url: ${ryhmasahkoposti-service-url:null}
  onr:
    enabled: ${onr.enabled:false}
    service-url: ${onr.service-url:https://virkailija.untuvaopintopolku.fi/oppijanumerorekisteri-service}
    cas:
      url: ${virkailija.cas.url:https://virkailija.untuvaopintopolku.fi/cas}
      username: ${oppijanumerorekisteri-service.rekisteri.username:username}
      password: ${oppijanumerorekisteri-service.rekisteri.password:password}
