package fi.oph.yki.util.exception;

public enum APIExceptionType {
  NOT_FOUND,
  PERSON_REGISTRATION_OID_MISMATCH,
  SESSION_OID_NOT_FOUND,
  KOSKI_EDUCATIONS_NOT_FOUND,
  FREE_REGISTRATIONS_EXHAUSTED,
  REGISTRATION_NOT_CANCELLABLE,
}
