package fi.oph.yki.util.exception;

public enum APIExceptionType {
  NOT_FOUND,
  PERSON_REGISTRATION_OID_MISMATCH,
  SESSION_OID_NOT_FOUND,
  KOSKI_EDUCATIONS_NOT_FOUND,
  FREE_REGISTRATIONS_EXHAUSTED,
  EXAM_DATE_CREATE_DUPLICATE_DATE,
  EXAM_DATE_REGISTRATION_END_BEFORE_START,
}
