package fi.oph.yki.model.type;

public enum EvaluationState {
  EVALUATION_PENDING, // ARVIOITAVA
  EVALUATION_COMPLETE, // ARVIOITU
  REVIEW_PENDING, // TARKISTUSARVIOITAVA
  REVIEW_COMPLETE, // TARKISTUSARVIOITU
  RETAKE_PENDING, // UUSITTAVA
  NO_SHOW, // EI_SUORITUSTA
  ABORTED, // KESKEYTETTY
}
