package fi.oph.yki.model.type;

public enum RegistrationState {
  EXPIRED,
  AWAITING_APPROVAL,
  COMPLETED,
  STARTED,
  SUBMITTED,
}
// PENDING,
// APPROVED,
// REJECTED,
// INFORMATION_REQUESTED,
// INFORMATION_REQUEST_ANSWERED,
