package fi.oph.otr.audit;

import fi.vm.sade.auditlog.Operation;

public enum OtrOperation implements Operation {
  LIST_INTERPRETERS,
  CREATE_INTERPRETER,
  GET_INTERPRETER,
  UPDATE_INTERPRETER,
  DELETE_INTERPRETER,
  CREATE_QUALIFICATION,
  UPDATE_QUALIFICATION,
  DELETE_QUALIFICATION,
  CREATE_MEETING_DATE,
  DELETE_MEETING_DATE,
  UPDATE_MEETING_DATE,
  PERSON_SEARCH_BY_IDENTITY_NUMBER,
}
