package fi.oph.vkt.audit;

import fi.vm.sade.auditlog.Operation;

public enum VktOperation implements Operation {
  LIST_EXAM_EVENTS,
  GET_EXAM_EVENT,
  GET_EXAM_EVENT_EXCEL,
  CREATE_EXAM_EVENT,
  UPDATE_EXAM_EVENT,
  UPDATE_ENROLLMENT,
  UPDATE_ENROLLMENT_STATUS,
  UPDATE_ENROLLMENT_PAYMENT_LINK,
  MOVE_ENROLLMENT,
  REFUND_PAYMENT,
  LIST_EXAMINER_DETAILS,
  GET_EXAMINER_INITIAL_DETAILS,
  VIEW_EXAMINER_CONTACT_REQUEST,
  VIEW_EXAMINER_ENROLLMENT,
  DELETE_EXAMINER_CONTACT_REQUEST,
  VIEW_EXAMINER_ENROLLMENT_HISTORY,
  CANCEL_ENROLLMENT_APPOINTMENT,
  VIEW_EXAMINER_ENROLLMENT_GRADES,
  CONVERT_EXAMINER_CONTACT_REQUEST_TO_APPOINTMENT,
  GET_SSN_BY_OID,
  GET_BIRTHDATE_BY_OID,
}
