export const PUBLIC_INTERPRETER_LOAD = 'PUBLIC_INTERPRETER/LOAD';
export const PUBLIC_INTERPRETER_LOADING = 'PUBLIC_INTERPRETER/LOADING';
export const PUBLIC_INTERPRETER_RECEIVED = 'PUBLIC_INTERPRETER/RECEIVED';
export const PUBLIC_INTERPRETER_ERROR = 'PUBLIC_INTERPRETER/ERROR';
export const PUBLIC_INTERPRETER_ADD_SELECTED =
  'PUBLIC_INTERPRETER/ADD_SELECTED';
export const PUBLIC_INTERPRETER_REMOVE_SELECTED =
  'PUBLIC_INTERPRETER/REMOVE_SELECTED';
export const PUBLIC_INTERPRETER_EMPTY_SELECTIONS =
  'PUBLIC_INTERPRETER/EMPTY_SELECTIONS';
export const PUBLIC_INTERPRETER_ADD_FILTERS = 'PUBLIC_INTERPRETER/ADD_FILTER';
export const PUBLIC_INTERPRETER_EMPTY_FILTERS =
  'PUBLIC_INTERPRETER/EMPTY_FILTERS';
export const PUBLIC_INTERPRETER_ADD_FILTER_ERROR =
  'PUBLIC_INTERPRETER/ADD_FILTER_ERROR';
export const PUBLIC_INTERPRETER_REMOVE_FILTER_ERROR =
  'PUBLIC_INTERPRETER/REMOVE_FILTER_ERROR';
