export const PUBLIC_INTERPRETER_LOAD = 'PUBLIC_INTERPRETER/LOAD';
export const PUBLIC_INTERPRETER_LOADING = 'PUBLIC_INTERPRETER/LOADING';
export const PUBLIC_INTERPRETER_RECEIVED = 'PUBLIC_INTERPRETER/RECEIVED';
export const PUBLIC_INTERPRETER_ERROR = 'PUBLIC_INTERPRETER/ERROR';
export const PUBLIC_INTERPRETER_ADD_FILTERS = 'PUBLIC_INTERPRETER/ADD_FILTER';
export const PUBLIC_INTERPRETER_EMPTY_FILTERS =
  'PUBLIC_INTERPRETER/EMPTY_FILTERS';
