export const CLERK_TRANSLATOR_LOAD = 'CLERK_TRANSLATOR/LOAD';
export const CLERK_TRANSLATOR_LOADING = 'CLERK_TRANSLATOR/LOADING';
export const CLERK_TRANSLATOR_ERROR = 'CLERK_TRANSLATOR/ERROR';
export const CLERK_TRANSLATOR_RECEIVED = 'CLERK_TRANSLATOR/RECEIVED';

export const CLERK_TRANSLATOR_SELECT = 'CLERK_TRANSLATOR/SELECT';
export const CLERK_TRANSLATOR_SELECT_ALL_FILTERED =
  'CLERK_TRANSLATOR/SELECT_ALL_FILTERED';
export const CLERK_TRANSLATOR_DESELECT = 'CLERK_TRANSLATOR/DESELECT';
export const CLERK_TRANSLATOR_DESELECT_ALL = 'CLERK_TRANSLATOR/DESELECT_ALL';

export const CLERK_TRANSLATOR_ADD_FILTER = 'CLERK_TRANSLATOR/ADD_FILTER';
export const CLERK_TRANSLATOR_RESET_FILTERS = 'CLERK_TRANSLATOR/RESET_FILTERS';
