export const PUBLIC_TRANSLATOR_LOAD = 'PUBLIC_TRANSLATOR/LOAD';
export const PUBLIC_TRANSLATOR_LOADING = 'PUBLIC_TRANSLATOR/LOADING';
export const PUBLIC_TRANSLATOR_RECEIVED = 'PUBLIC_TRANSLATOR/RECEIVED';
export const PUBLIC_TRANSLATOR_ERROR = 'PUBLIC_TRANSLATOR/ERROR';
export const PUBLIC_TRANSLATOR_ADD_SELECTED = 'PUBLIC_TRANSLATOR/ADD_SELECTED';
export const PUBLIC_TRANSLATOR_REMOVE_SELECTED =
  'PUBLIC_TRANSLATOR/REMOVE_SELECTED';
export const PUBLIC_TRANSLATOR_EMPTY_SELECTIONS =
  'PUBLIC_TRANSLATOR/EMPTY_SELECTIONS';
export const PUBLIC_TRANSLATOR_ADD_FILTERS = 'PUBLIC_TRANSLATOR/ADD_FILTER';
export const PUBLIC_TRANSLATOR_EMPTY_FILTERS =
  'PUBLIC_TRANSLATOR/EMPTY_FILTERS';
export const PUBLIC_TRANSLATOR_ADD_FILTER_ERROR =
  'PUBLIC_TRANSLATOR/ADD_FILTER_ERROR';
export const PUBLIC_TRANSLATOR_REMOVE_FILTER_ERROR =
  'PUBLIC_TRANSLATOR/REMOVE_FILTER_ERROR';
