server:
  servlet:
    session:
      cookie:
        secure: false
app:
  reservation:
    duration: PT5M
  payment:
    paytrail:
      url: https://services.paytrail.com
      secret: SAIPPUAKAUPPIAS
      account: 375917
