server:
  servlet:
    session:
      cookie:
        secure: false
app:
  reservation:
    duration: PT5M
  payment:
    paytrail:
      secret: SAIPPUAKAUPPIAS
      account: 375917
  featureFlags:
    freeEnrollmentAllowed: true
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

