--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Debian 12.9-1.pgdg110+1)
-- Dumped by pg_dump version 14.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: kielipari; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kielipari (
    id bigint NOT NULL,
    oikeustulkki bigint NOT NULL,
    kielesta character varying(10) NOT NULL,
    kieleen character varying(10) NOT NULL,
    voimassaolo_alkaa date NOT NULL,
    voimassaolo_paattyy date NOT NULL
);


ALTER TABLE public.kielipari OWNER TO postgres;

--
-- Name: kielipari_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kielipari ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kielipari_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oikeustulkki; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oikeustulkki (
    id bigint NOT NULL,
    tulkki bigint NOT NULL,
    lisatiedot text,
    muokattu timestamp without time zone,
    muokkaaja text,
    luotu timestamp without time zone DEFAULT now() NOT NULL,
    luoja text NOT NULL,
    tutkinto_tyyppi character varying(64) DEFAULT 'NULL::character varying'::character varying NOT NULL,
    julklaisulupa_email boolean DEFAULT false NOT NULL,
    julklaisulupa_puhelinnumero boolean DEFAULT false NOT NULL,
    julklaisulupa_muu_yhteystieto boolean DEFAULT false NOT NULL,
    poistettu boolean DEFAULT false NOT NULL,
    poistohetki timestamp without time zone,
    poistaja text,
    version bigint DEFAULT 0 NOT NULL,
    muu_yhteystieto text,
    julkaisulupa boolean DEFAULT false NOT NULL,
    CONSTRAINT tutkinto_tyyppi_check CHECK (((tutkinto_tyyppi)::text = ANY (ARRAY[('OIKEUSTULKIN_ERIKOISAMMATTITUTKINTO'::character varying)::text, ('MUU_KORKEAKOULUTUTKINTO'::character varying)::text])))
);


ALTER TABLE public.oikeustulkki OWNER TO postgres;

--
-- Name: oikeustulkki_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oikeustulkki ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oikeustulkki_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oikeustulkki_muokkaus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oikeustulkki_muokkaus (
    id bigint NOT NULL,
    oikeustulkki bigint NOT NULL,
    muokattu timestamp without time zone DEFAULT now() NOT NULL,
    muokkaaja text NOT NULL,
    muokkausviesti text
);


ALTER TABLE public.oikeustulkki_muokkaus OWNER TO postgres;

--
-- Name: oikeustulkki_muokkaus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oikeustulkki_muokkaus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oikeustulkki_muokkaus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sahkoposti_muistutus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sahkoposti_muistutus (
    id bigint NOT NULL,
    luotu timestamp without time zone DEFAULT now(),
    oikeustulkki bigint NOT NULL,
    lahetetty timestamp without time zone,
    lahettaja text NOT NULL,
    vastaanottaja text NOT NULL,
    template_name text NOT NULL,
    sahkoposti_id bigint,
    kieli character varying(3) NOT NULL,
    virhe text
);


ALTER TABLE public.sahkoposti_muistutus OWNER TO postgres;

--
-- Name: sahkoposti_muistutus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sahkoposti_muistutus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sahkoposti_muistutus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sijainti; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sijainti (
    id bigint NOT NULL,
    oikeustulkki bigint NOT NULL,
    tyyppi character varying(10) NOT NULL,
    koodi character varying(16),
    CONSTRAINT sijainti_tyyppi_check CHECK ((((tyyppi)::text = ANY (ARRAY[('MAAKUNTA'::character varying)::text, ('KOKO_SUOMI'::character varying)::text])) AND ((((tyyppi)::text = 'KOKO_SUOMI'::text) AND (koodi IS NULL)) OR (((tyyppi)::text <> 'KOKO_SUOMI'::text) AND (koodi IS NOT NULL)))))
);


ALTER TABLE public.sijainti OWNER TO postgres;

--
-- Name: sijainti_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sijainti ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sijainti_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tulkki; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tulkki (
    id bigint NOT NULL,
    henkilo_oid text NOT NULL,
    muokattu timestamp without time zone,
    muokkaaja text,
    luotu timestamp without time zone DEFAULT now() NOT NULL,
    luoja text NOT NULL,
    poistettu boolean DEFAULT false NOT NULL,
    poistohetki timestamp without time zone,
    poistaja text,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.tulkki OWNER TO postgres;

--
-- Name: tulkki_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tulkki ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tulkki_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kielipari kielipari_oikeustulkki_kielesta_kieleen_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kielipari
    ADD CONSTRAINT kielipari_oikeustulkki_kielesta_kieleen_key UNIQUE (oikeustulkki, kielesta, kieleen);


--
-- Name: kielipari kielipari_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kielipari
    ADD CONSTRAINT kielipari_pkey PRIMARY KEY (id);


--
-- Name: oikeustulkki_muokkaus oikeustulkki_muokkaus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oikeustulkki_muokkaus
    ADD CONSTRAINT oikeustulkki_muokkaus_pkey PRIMARY KEY (id);


--
-- Name: oikeustulkki oikeustulkki_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oikeustulkki
    ADD CONSTRAINT oikeustulkki_pkey PRIMARY KEY (id);


--
-- Name: sahkoposti_muistutus sahkoposti_muistutus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sahkoposti_muistutus
    ADD CONSTRAINT sahkoposti_muistutus_pkey PRIMARY KEY (id);


--
-- Name: sijainti sijainti_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sijainti
    ADD CONSTRAINT sijainti_pkey PRIMARY KEY (id);


--
-- Name: tulkki tulkki_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tulkki
    ADD CONSTRAINT tulkki_pkey PRIMARY KEY (id);


--
-- Name: kielipari kielipari_oikeustulkki_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kielipari
    ADD CONSTRAINT kielipari_oikeustulkki_fkey FOREIGN KEY (oikeustulkki) REFERENCES public.oikeustulkki(id);


--
-- Name: oikeustulkki_muokkaus oikeustulkki_muokkaus_oikeustulkki_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oikeustulkki_muokkaus
    ADD CONSTRAINT oikeustulkki_muokkaus_oikeustulkki_fkey FOREIGN KEY (oikeustulkki) REFERENCES public.oikeustulkki(id);


--
-- Name: oikeustulkki oikeustulkki_tulkki_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oikeustulkki
    ADD CONSTRAINT oikeustulkki_tulkki_fkey FOREIGN KEY (tulkki) REFERENCES public.tulkki(id);


--
-- Name: sahkoposti_muistutus sahkoposti_muistutus_oikeustulkki_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sahkoposti_muistutus
    ADD CONSTRAINT sahkoposti_muistutus_oikeustulkki_fkey FOREIGN KEY (oikeustulkki) REFERENCES public.oikeustulkki(id);


--
-- Name: sijainti sijainti_oikeustulkki_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sijainti
    ADD CONSTRAINT sijainti_oikeustulkki_fkey FOREIGN KEY (oikeustulkki) REFERENCES public.oikeustulkki(id);


--
-- PostgreSQL database dump complete
--

