--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Debian 12.9-1.pgdg110+1)
-- Dumped by pg_dump version 14.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: interpreter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interpreter (
    interpreter_id bigint NOT NULL,
    modified_at timestamp without time zone,
    modified_by text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    created_by text,
    deleted_at timestamp without time zone,
    deleted_by text,
    version integer DEFAULT 0 NOT NULL,
    onr_id character varying(255) NOT NULL,
    permission_to_publish_email boolean NOT NULL,
    permission_to_publish_phone boolean NOT NULL,
    other_contact_information text,
    permission_to_publish_other_contact_information boolean NOT NULL,
    extra_information text
);


ALTER TABLE public.interpreter OWNER TO postgres;

--
-- Name: interpreter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interpreter ALTER COLUMN interpreter_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interpreter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: language_pair; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.language_pair (
    language_pair_id bigint NOT NULL,
    qualification_id bigint NOT NULL,
    from_lang character varying(10) NOT NULL,
    to_lang character varying(10) NOT NULL,
    begin_date date NOT NULL,
    end_date date NOT NULL,
    modified_at timestamp without time zone,
    modified_by text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    created_by text,
    deleted_at timestamp without time zone,
    deleted_by text,
    version integer DEFAULT 0 NOT NULL,
    CONSTRAINT ck_language_pair_from_to CHECK (((from_lang)::text <> (to_lang)::text))
);


ALTER TABLE public.language_pair OWNER TO postgres;

--
-- Name: language_pair_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.language_pair ALTER COLUMN language_pair_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.language_pair_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oikeustulkki_muokkaus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oikeustulkki_muokkaus (
    id bigint NOT NULL,
    oikeustulkki bigint NOT NULL,
    muokattu timestamp without time zone DEFAULT now() NOT NULL,
    muokkaaja text NOT NULL,
    muokkausviesti text
);


ALTER TABLE public.oikeustulkki_muokkaus OWNER TO postgres;

--
-- Name: oikeustulkki_muokkaus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oikeustulkki_muokkaus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oikeustulkki_muokkaus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qualification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.qualification (
    qualification_id bigint NOT NULL,
    interpreter_id bigint NOT NULL,
    modified_at timestamp without time zone,
    modified_by text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    created_by text,
    deleted_at timestamp without time zone,
    deleted_by text,
    version integer DEFAULT 0 NOT NULL,
    permission_to_publish boolean NOT NULL,
    examination_type character varying(255) NOT NULL
);


ALTER TABLE public.qualification OWNER TO postgres;

--
-- Name: qualification_examination_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.qualification_examination_type (
    name character varying(255) NOT NULL
);


ALTER TABLE public.qualification_examination_type OWNER TO postgres;

--
-- Name: qualification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.qualification ALTER COLUMN qualification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qualification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: region; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.region (
    region_id bigint NOT NULL,
    interpreter_id bigint NOT NULL,
    code character varying(16) NOT NULL,
    modified_at timestamp without time zone,
    modified_by text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    created_by text,
    deleted_at timestamp without time zone,
    deleted_by text,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.region OWNER TO postgres;

--
-- Name: region_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.region ALTER COLUMN region_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.region_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sahkoposti_muistutus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sahkoposti_muistutus (
    id bigint NOT NULL,
    luotu timestamp without time zone DEFAULT now(),
    oikeustulkki bigint NOT NULL,
    lahetetty timestamp without time zone,
    lahettaja text NOT NULL,
    vastaanottaja text NOT NULL,
    template_name text NOT NULL,
    sahkoposti_id bigint,
    kieli character varying(3) NOT NULL,
    virhe text
);


ALTER TABLE public.sahkoposti_muistutus OWNER TO postgres;

--
-- Name: sahkoposti_muistutus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sahkoposti_muistutus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sahkoposti_muistutus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interpreter interpreter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interpreter
    ADD CONSTRAINT interpreter_pkey PRIMARY KEY (interpreter_id);


--
-- Name: language_pair language_pair_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language_pair
    ADD CONSTRAINT language_pair_pkey PRIMARY KEY (language_pair_id);


--
-- Name: oikeustulkki_muokkaus oikeustulkki_muokkaus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oikeustulkki_muokkaus
    ADD CONSTRAINT oikeustulkki_muokkaus_pkey PRIMARY KEY (id);


--
-- Name: qualification_examination_type qualification_examination_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qualification_examination_type
    ADD CONSTRAINT qualification_examination_type_pkey PRIMARY KEY (name);


--
-- Name: qualification qualification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qualification
    ADD CONSTRAINT qualification_pkey PRIMARY KEY (qualification_id);


--
-- Name: region region_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.region
    ADD CONSTRAINT region_pkey PRIMARY KEY (region_id);


--
-- Name: sahkoposti_muistutus sahkoposti_muistutus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sahkoposti_muistutus
    ADD CONSTRAINT sahkoposti_muistutus_pkey PRIMARY KEY (id);


--
-- Name: interpreter uk_interpreter_onr_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interpreter
    ADD CONSTRAINT uk_interpreter_onr_id UNIQUE (onr_id);


--
-- Name: region uk_region_interpreter_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.region
    ADD CONSTRAINT uk_region_interpreter_code UNIQUE (interpreter_id, code);


--
-- Name: language_pair fk_language_pair_qualification; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language_pair
    ADD CONSTRAINT fk_language_pair_qualification FOREIGN KEY (qualification_id) REFERENCES public.qualification(qualification_id);


--
-- Name: oikeustulkki_muokkaus fk_oikeustulkki_muokkaus_oikeustulkki; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oikeustulkki_muokkaus
    ADD CONSTRAINT fk_oikeustulkki_muokkaus_oikeustulkki FOREIGN KEY (oikeustulkki) REFERENCES public.qualification(qualification_id);


--
-- Name: qualification fk_qualification_examination_type; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qualification
    ADD CONSTRAINT fk_qualification_examination_type FOREIGN KEY (examination_type) REFERENCES public.qualification_examination_type(name);


--
-- Name: qualification fk_qualification_interpreter; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qualification
    ADD CONSTRAINT fk_qualification_interpreter FOREIGN KEY (interpreter_id) REFERENCES public.interpreter(interpreter_id);


--
-- Name: region fk_region_interpreter; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.region
    ADD CONSTRAINT fk_region_interpreter FOREIGN KEY (interpreter_id) REFERENCES public.interpreter(interpreter_id);


--
-- Name: sahkoposti_muistutus fk_sahkoposti_muistutus_oikeustulkki; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sahkoposti_muistutus
    ADD CONSTRAINT fk_sahkoposti_muistutus_oikeustulkki FOREIGN KEY (oikeustulkki) REFERENCES public.qualification(qualification_id);


--
-- PostgreSQL database dump complete
--

