export const CLERK_NEW_TRANSLATOR_UPDATE = 'CLERK_NEW_TRANSLATOR/UPDATE';
export const CLERK_NEW_TRANSLATOR_RESET_REQUEST_STATUS =
  'CLERK_NEW_TRANSLATOR/RESET_REQUEST_STATUS';
export const CLERK_NEW_TRANSLATOR_RESET_DETAILS =
  'CLERK_NEW_TRANSLATOR/RESET_DETAILS';
export const CLERK_NEW_TRANSLATOR_SAVE = 'CLERK_NEW_TRANSLATOR/SAVE';
export const CLERK_NEW_TRANSLATOR_SUCCESS = 'CLERK_NEW_TRANSLATOR/SUCCESS';
export const CLERK_NEW_TRANSLATOR_ERROR = 'CLERK_NEW_TRANSLATOR/ERROR';
