export const NOTIFIER_DIALOG_ADD = 'NOTIFIER_DIALOG/ADD';
export const NOTIFIER_DIALOG_REMOVE = 'NOTIFIER_DIALOG/REMOVE';

export const NOTIFIER_TOAST_ADD = 'NOTIFIER_TOAST/ADD';
export const NOTIFIER_TOAST_REMOVE = 'NOTIFIER_TOAST/REMOVE';

export const NOTIFIER_ACTION_DO_NOTHING = 'NOTIFIER_ACTION/DO_NOTHING';

// Contact Request Actions
export const NOTIFIER_ACTION_CONTACT_REQUEST_RESET =
  'NOTIFIER_ACTION_CONTACT_REQUEST/RESET';
export const NOTIFIER_ACTION_CONTACT_REQUEST_EMPTY =
  'NOTIFIER_ACTION_CONTACT_REQUEST/EMPTY';

// Actions for ClerkTranslatorEmail
export const NOTIFIER_ACTION_CLERK_TRANSLATOR_EMAIL_RESET =
  'NOTIFIER_ACTION_CLERK_TRANSLATOR_EMAIL/RESET';
export const NOTIFIER_ACTION_CLERK_TRANSLATOR_EMAIL_SEND =
  'NOTIFIER_ACTION_CLERK_TRANSLATOR_EMAIL/SEND';

// Actions for ClerkTranslatorDetails
export const NOTIFIER_ACTION_CLERK_TRANSLATOR_DETAILS_CANCEL_UPDATE =
  'NOTIFIER_ACTION_CLERK_TRANSLATOR_DETAILS/CANCEL_UPDATE';
