package fi.oph.yki.audit;

import fi.vm.sade.auditlog.Operation;

public enum YkiOperation implements Operation {
  GET_APPROVAL,
  UPDATE_APPROVAL,
  LIST_APPROVALS,
  SEND_SUPPLEMENT_REQUEST,
  ADD_COMMENT,
  CREATE_FREE_REGISTRATION,
  UPDATE_FREE_REGISTRATION,
  UPDATE_PERSON_CONTACT_DETAILS,
  MOVE_REGISTRATION,
  CANCEL_REGISTRATION,
  GET_CUSTOMER_DETAILS,
  SEARCH_CUSTOMERS,
  CREATE_EXAM_DATE,
  UPDATE_EXAM_DATE,
  UPDATE_EVALUATION,
  DELETE_EXAM_DATE,
  GET_QUARANTINE_MATCHES,
  GET_QUARANTINE_REVIEWS,
  GET_ACTIVE_QUARANTINES,
  SET_QUARANTINE_REVIEW,
  CREATE_QUARANTINE,
  UPDATE_QUARANTINE,
  DELETE_QUARANTINE,
}
