name: AKR

on:
  workflow_dispatch:
  push:
    paths:
      - "backend/akr/**"
      - "frontend/packages/akr/**"
      - "!**/*.md"
    # Setting 'branches' has the side effect that just pushing tags does not start workflows.
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    uses: ./.github/workflows/common-frontend.yml
    with:
      app-name: "akr"
      cypress-base-url: "http://localhost:4000"
  backend:
    needs: frontend
    uses: ./.github/workflows/common-backend.yml
    with:
      app-name: "akr"
  deploy:
    needs: backend
    uses: ./.github/workflows/common-deploy.yml
    with:
      app-name: "akr"
      image-name: "akr"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
