name: OTR

on:
  workflow_dispatch:
  push:
    paths:
      - "backend/otr/**"
      - "frontend/packages/otr/**"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    uses: ./.github/workflows/common-frontend.yml
    with:
      app-name: "otr"
  backend:
    needs: frontend
    uses: ./.github/workflows/common-backend.yml
    with:
      app-name: "otr"
  deploy:
    needs: backend
    uses: ./.github/workflows/common-deploy.yml
    with:
      app-name: "otr"
      image-name: "oikeustulkkirekisteri"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
