name: VKT

on:
  workflow_dispatch:
  push:
    paths:
      - "backend/vkt/**"
      - "frontend/packages/vkt/**"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    uses: ./.github/workflows/common-frontend.yml
    with:
      app-name: "vkt"
      cypress-base-url: "http://localhost:4002"
  backend:
    needs: frontend
    uses: ./.github/workflows/common-backend.yml
    with:
      app-name: "vkt"
  deploy:
    needs: backend
    uses: ./.github/workflows/common-deploy.yml
    with:
      app-name: "vkt"
      image-name: "vkt"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
